backend:
  name: git-gateway
  branch: master

media_folder: static/images/uploads
public_folder: /images/uploads

site_url: https://www.satugulle.fi

collections:
  - name: settings
    label: Settings
    files:
      - file: settings/navigation.yml
        label: Navigation
        name: navigation
        fields:
          - label: Navigation
            name: nav_items
            widget: list
            fields:
              - { label: Label, name: label, widget: string }
              - { label: Path, name: path, widget: string }

  - name: "front_page"
    label: "Frontpage"
    folder: "content/front_page"
    create: false
    slug: "index"
    media_folder: ""
    public_folder: ""
    path: "{{title}}/index"
    editor:
      preview: false
    fields:
      - { label: "Type", name: "type", widget: "hidden", default: "front_page" }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - {
          label: "Description",
          name: "description",
          widget: "string",
          required: false,
        }
      - {
          label: "Main image",
          name: "main_image",
          widget: "image",
          allow_multiple: false,
          required: false,
        }
      - { label: "Body", name: "body", widget: "markdown", required: false }
      - { label: "Path", name: "path", widget: "string" }

  - name: "basic_page"
    label: "Basic page"
    folder: "content/basic_page"
    create: true
    slug: "index"
    media_folder: ""
    public_folder: ""
    path: "{{title}}/index"
    editor:
      preview: false
    fields:
      - { label: "Type", name: "type", widget: "hidden", default: "basic_page" }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - {
          label: "Description",
          name: "description",
          widget: "string",
          required: false,
        }
      - {
          label: "Main image",
          name: "main_image",
          widget: "image",
          allow_multiple: false,
          required: false,
        }
      - { label: "Body", name: "body", widget: "markdown", required: false }
      - { label: "Path", name: "path", widget: "string" }

  - name: "blog_post"
    label: "Blog post"
    folder: "content/blog_post"
    create: true
    slug: "index"
    media_folder: ""
    public_folder: ""
    path: "{{title}}/index"
    editor:
      preview: false
    fields:
      - { label: "Type", name: "type", widget: "hidden", default: "blog_post" }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - {
          label: "Description",
          name: "description",
          widget: "string",
          required: false,
        }
      - {
          label: "Main image",
          name: "main_image",
          widget: "image",
          allow_multiple: false,
          required: false,
        }
      - { label: "Text", name: "body", widget: "markdown" }
      - { label: "Path", name: "path", widget: "string" }

  - name: "service"
    label: "Service"
    folder: "content/service"
    create: true
    slug: "index"
    media_folder: ""
    public_folder: ""
    path: "{{title}}/index"
    editor:
      preview: false
    fields:
      - { label: "Type", name: "type", widget: "hidden", default: "service" }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - {
          label: "Description",
          name: "description",
          widget: "string",
          required: false,
        }
      - {
          label: "Main image",
          name: "main_image",
          widget: "image",
          allow_multiple: false,
          required: false,
        }
      - { label: "Text", name: "body", widget: "markdown" }
      - label: Customer feedback
        name: customer_feedback
        widget: list
        fields:
          - { label: Customer name, name: customer_name, widget: string }
          - { label: Text, name: text, widget: text }
          - { label: Link url, name: url, widget: string }
      - { label: "Path", name: "path", widget: "string" }
